### ISSUE TITLE
Articoli Farina e Malham

### ISSUE THREAD

**Issue by grammaton** [s-e-a-m/References#1]
@s-e-a-m/smerm ho due cartelle di articoli da caricare, una di farina e una di malham, non è tanto materiale. Ma le vorrei caricare solo se qualcuno si prende in carico di rinominare i file. 

Regole:
 - `no-spazi`
 - `YEAR-LASTNAME-Title.pdf`

Come già fatto nelle cartelle già caricate.
Qualcuno se la sente?

G.

**Comment by Edd95** [comment]
Lo faccio volentieri :)

Il giorno dom 5 apr 2020 alle ore 18:44 Giuseppe Silvi <
notifications@github.com> ha scritto:

**Comment by grammaton** [comment]
li carico allora, grazie
g

**Comment by grammaton** [comment]
caricati @Edd95 
buon divertimento.

grazie
